"""Added index on (name, time)

Revision ID: 00e17abca90b
Revises: 1e3567d579ab
Create Date: 2020-04-11 16:12:40.632663

"""
import sqlalchemy as sa
from alembic import op

Session = sa.orm.sessionmaker()


# revision identifiers, used by Alembic.
revision = '00e17abca90b'
down_revision = '1e3567d579ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('price_data_time_idx', table_name='price_data')
    # ### end Alembic commands ###
    op.create_index('price_data_name_time_idx', 'price_data', [sa.text('name DESC'), 'time'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('price_data_time_idx', 'price_data',
                    ['time'], unique=False)
    # ### end Alembic commands ###

    op.drop_index('price_data_name_time_idx', table_name='price_data')
