"""Initial migration

Revision ID: 373012ff4dd0
Revises: 
Create Date: 2020-04-03 16:47:55.999560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373012ff4dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_data',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('members', sa.Boolean(), nullable=False),
    sa.Column('buy_average', sa.Integer(), nullable=False),
    sa.Column('buy_quantity', sa.Integer(), nullable=False),
    sa.Column('sell_average', sa.Integer(), nullable=False),
    sa.Column('sell_quantity', sa.Integer(), nullable=False),
    sa.Column('overall_average', sa.Integer(), nullable=False),
    sa.Column('overall_quantity', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text("date_trunc('hour', NOW()) + INTERVAL '5 min' * ROUND(date_part('minute', NOW()) / 5.0)"), nullable=False),
    sa.PrimaryKeyConstraint('item_id', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_data')
    # ### end Alembic commands ###
