"""Initial migration

Revision ID: 50a840a3afc0
Revises:
Create Date: 2020-06-09 00:07:47.876273

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '50a840a3afc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
                    sa.Column('id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('members', sa.Boolean(), nullable=False),
                    sa.Column('buy_limit', sa.Integer(),
                              server_default='-1', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_index('item_members_buylimit_idx', 'item', [
                    sa.text('members DESC'), 'buy_limit'], unique=False)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_table('price_data',
                    sa.Column('id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('members', sa.Boolean(), nullable=False),
                    sa.Column('buy_average', sa.Integer(), nullable=False),
                    sa.Column('buy_quantity', sa.Integer(), nullable=False),
                    sa.Column('sell_average', sa.Integer(), nullable=False),
                    sa.Column('sell_quantity', sa.Integer(), nullable=False),
                    sa.Column('overall_average', sa.Integer(), nullable=False),
                    sa.Column('overall_quantity',
                              sa.Integer(), nullable=False),
                    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text(
                        "date_trunc('hour', NOW()) + INTERVAL '5 min' * ROUND(date_part('minute', NOW()) / 5.0)"), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['item.id'], ),
                    sa.PrimaryKeyConstraint('id', 'time')
                    )
    op.create_index('price_data_members_time_idx', 'price_data', [
                    sa.text('members DESC'), 'time'], unique=False)
    op.create_index('price_data_name_time_idx', 'price_data', [
                    sa.text('name DESC'), 'time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('price_data_name_time_idx', table_name='price_data')
    op.drop_index('price_data_members_time_idx', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index('item_members_buylimit_idx', table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
