"""Added indices properly

Revision ID: 9cfc62c232ee
Revises: 1bea84af32db
Create Date: 2020-04-29 18:56:49.447706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfc62c232ee'
down_revision = '1bea84af32db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('price_data_members_time_idx', 'price_data', [sa.text('members DESC'), 'time'], unique=False)
    op.create_index('price_data_name_time_idx', 'price_data', [sa.text('name DESC'), 'time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('price_data_name_time_idx', table_name='price_data')
    op.drop_index('price_data_members_time_idx', table_name='price_data')
    # ### end Alembic commands ###
