"""Added indices to items cache table

Revision ID: d6f0ca02a751
Revises: 1bea84af32db
Create Date: 2020-05-09 22:18:53.751880

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd6f0ca02a751'
down_revision = '1bea84af32db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('item_id_idx', 'item', ['id'], unique=False)
    op.create_index('item_members_buylimit_idx', 'item', [sa.text('members DESC'), 'buy_limit'], unique=False)
    op.create_index('item_name_idx', 'item', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('item_name_idx', table_name='item')
    op.drop_index('item_members_buylimit_idx', table_name='item')
    op.drop_index('item_id_idx', table_name='item')
    # ### end Alembic commands ###
